# Generated by Django 3.0.3 on 2020-06-06 14:41

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateField(default=datetime.date(2020, 6, 6))),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
