# Generated by Django 3.0.6 on 2020-06-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200529_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
