# Generated by Django 3.0.6 on 2020-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200604_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituition', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=30)),
                ('present', models.BooleanField(default=False)),
                ('end', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='media/images/extracurricular/')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituition', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=30)),
                ('present', models.BooleanField(default=False)),
                ('end', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='media/images/jobs/')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/images/education/'),
        ),
    ]
