# Generated by Django 3.0.6 on 2020-06-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200604_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracurricular',
            name='result',
        ),
        migrations.RemoveField(
            model_name='job',
            name='result',
        ),
    ]
